---
abstract: 'Pi as related by Abrahamic tradition.'
author:
  - 'Ashley Pond V · ashley@cpan.org · L<http://pangyresoft.com>.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Pi-Abrahamic
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/pangyre/p5-acme-pi-abrahamic-
version: 7.7
